name: dotnet-tbd
run-name: Build and deploy to Notino K8S (started ${{ github.actor }})

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: remunda/dotnet-test/.github/workflows/build-dotnet.yml@main
    with:
      config-path: "not"
